### PR TITLE
Cmm0032 branch

### PR DESCRIPTION
**Pull request by CMayer0032**
The only changes I made where in regards to the HTML. Nothing else should change. If anything else does change, email me and revert to the previous instance. Sorry. this is my first time doing this. ^^;

### CODE REVIEW

**Comment by dsh0005** [comment]
kthx looks good i guess.

**Comment by CMayer0032** [comment]
Can I add those as we add the URLs? Or do I need to do them tomorrow? And does that include the images that are pulled from the database?

**Comment by dsh0005** [comment]
Sure, and no, images from imagefields use the variable binding.

**Comment by CMayer0032** [comment]
I'll be sure to update that tomorrow.

**Pull request merged**
